[project]
name = "browser-use-demo"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "browser-use>=0.11.8",
    "langchain-openai>=1.1.7",
    "playwright>=1.58.0",
]
